<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-F4KJESH" ignored="0" name="Cucumber Tests iOS" tests="3" failures="0" timestamp="2022-01-26T02:32:29 IST" time="0.374" errors="0">
  <testcase name="@BeforeMethod setUp" time="0.01" classname="com.browserstack.examples.pages.TestBase">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at com.browserstack.examples.pages.TestBase.setUp(TestBase.java:62)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase name="@BeforeMethod setUp" time="0.01" classname="com.browserstack.examples.pages.TestBase">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at com.browserstack.examples.pages.TestBase.setUp(TestBase.java:62)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase name="@BeforeMethod setUp" time="0.01" classname="com.browserstack.examples.pages.TestBase">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at com.browserstack.examples.pages.TestBase.setUp(TestBase.java:62)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase name="@AfterMethod tearDown" time="-1.643144549567E9" classname="com.browserstack.examples.pages.TestBase">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterMethod tearDown" time="-1.643144549569E9" classname="com.browserstack.examples.pages.TestBase">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterMethod tearDown" time="-1.64314454957E9" classname="com.browserstack.examples.pages.TestBase">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="feature" time="0.0" classname="com.browserstack.examples.tests.RunAppiumCucumberTests">
    <skipped/>
  </testcase> <!-- feature -->
  <testcase name="feature" time="0.0" classname="com.browserstack.examples.tests.RunAppiumCucumberTests">
    <skipped/>
  </testcase> <!-- feature -->
  <testcase name="feature" time="0.0" classname="com.browserstack.examples.tests.RunAppiumCucumberTests">
    <skipped/>
  </testcase> <!-- feature -->
</testsuite> <!-- Cucumber Tests iOS -->
